### ISSUE TITLE
Add git to Docker image

### ISSUE THREAD

**Issue by nilic** [cytopia/docker-terraform-docs#31]
Hi, could you consider adding git to your terraform-docs image? 

This would be very useful for integrating with CI/CD - eg. for using `git diff` in mono-repos to check whether Terraform-related files have changed and running some steps based on that, or using this image in CI/CD to recreate and push docs as an alternative to running terraform-docs in a git pre/post-commit hook.

Git itself would add some 19MiB to the image:

```bash
+ apk add --no-cache git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20190108-r0)
(2/7) Installing nghttp2-libs (1.39.2-r0)
(3/7) Installing libssh2 (1.9.0-r1)
(4/7) Installing libcurl (7.61.1-r3)
(5/7) Installing expat (2.2.8-r0)
(6/7) Installing pcre2 (10.31-r0)
(7/7) Installing git (2.18.2-r0)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 19 MiB in 20 packages
```

Thanks!

**Comment by cytopia** [comment]
@nilic I am afraid, this is going to increase the size way too much. I've tried my best to keep it as small as possible.

If you need git in your pipeline

1. use an additional git docker image
2. or build your custom image based on this one and by adding git to it


For 2.:

```Dockerfile
ARG VERSION
FROM cytopia/terraform-docs:${VERSION}
RUN apk add --no-cache git
```
