### ISSUE TITLE
Latest image (0.8.0?) results in `terraform-docs-012: not found`

### ISSUE THREAD

**Issue by Andrew-Sheridan** [cytopia/docker-terraform-docs#32]
Running this:

```text
docker run --rm \
  -v $(pwd):/data \
  cytopia/terraform-docs \
  terraform-docs-012 --sort-inputs-by-required --with-aggregate-type-defaults md . > README.md
```

Results in this:
```text
/docker-entrypoint.sh: exec: line 144: terraform-docs-012: not found
```

But setting tag to `0.7.0`  like this 
```text
docker run --rm \
  -v $(pwd):/data \
  cytopia/terraform-docs:0.7.0 \
  terraform-docs-012 --sort-inputs-by-required --with-aggregate-type-defaults md . > README.md
```
results in the `README.md` file being populated.

Thank you for your time, please let me know if you have any questions.

**Comment by cytopia** [comment]
Working on it. FYI: As you output this to your README anyway, consider using `terraform-docs-replace-012` which can also inline update your README.

**Comment by Andrew-Sheridan** [comment]
> terraform-docs-replace-012

I'm not sure if I'm executing this wrong, but 
```text
docker run --rm   -v $(pwd):/data   cytopia/terraform-docs:0.7.0   terraform-docs-replace-012 --sort-inputs-by-required --with-aggregate-type-defaults md . > README.md
```
Gives me
```text
Error, . not found in: /data/.
```

**Comment by cytopia** [comment]
This should rather be (If the README has the default delimiter in where in between the data should be replaed):
```bash
docker run --rm   -v $(pwd):/data cytopia/terraform-docs:0.7.0 terraform-docs-replace-012 --sort-inputs-by-required --with-aggregate-type-defaults md README.md
```

**Comment by cytopia** [comment]
@Andrew-Sheridan 
Can you try out if `cytopia/terraform-docs:0.8.1-release-0.18` for you without any issues

**Comment by Andrew-Sheridan** [comment]
@cytopia `0.8.1-release-0.18` appears to work without error.

Thank you for your attention and efforts on this.
