### ISSUE TITLE
Question - Does this support tf version 0.14.7 ?

### ISSUE THREAD

**Issue by kristijorgji** [cytopia/docker-terraform-docs#44]
From readme table can not understand what version of docker-terraform-docs works with a particular tf version.

I was learning and playing around with tf 0.14.7, and tried 
`cytopia/terraform-docs:0.10.1`
latest docs image but did not work, and also error does not have many information why:

```
docker run --rm -it \
-v /Users/kristi.jorgji/tf-learn/modules/dummy:/data \
cytopia/terraform-docs:0.10.1 \
terraform-docs-replace --sort-inputs-by-required --with-aggregate-type-defaults md README.md

terraform-docs --sort-inputs-by-required --with-aggregate-type-defaults md .
Failed
make: *** [terraform-docs] Error 1
```

**Comment by cytopia** [comment]
Not sure what is supported in their [upstream](https://github.com/terraform-docs/terraform-docs) Regardless, Docker images have just been updated and you can try the `:latest` tag which is based on their master.
