### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by FernandoMiguel** [cytopia/docker-terraform-docs#52]
are you planning on adding ARM / Apple Silicone dockerfile support?

thanks in advance

**Comment by cytopia** [comment]
Yes, that's currently in the pipeline

**Comment by cytopia** [comment]
@FernandoMiguel should be available shortly via: https://github.com/cytopia/docker-terraform-docs/pull/53

**Comment by cytopia** [comment]
Merged, will be available once the build pipelines have finished (1-2 hours)

* https://github.com/cytopia/docker-terraform-docs/actions/runs/3330839242
* https://github.com/cytopia/docker-terraform-docs/actions/runs/3330849834
